global:
  scrape_interval:     5s 
  evaluation_interval: 5s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:5013']
  
  - job_name: 'working-good'
    static_configs:
      - targets: ['host.docker.internal:5001']