version: '3.7'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: SqlServer
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SafePassword123!
    ports:
      - 5010:1433
  seq:
    image: datalust/seq
    container_name: Seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5011:80
  vault:
    image: vault:1.13.3
    container_name: Vault
    restart: unless-stopped
    ports:
      - 5012:8200
    environment:
      - VAULT_ADDR=http://127.0.0.1:5012
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK