version: '3.7'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: SqlServer
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SafePassword123!
    ports:
      - 5010:1433
  seq:
    image: datalust/seq
    container_name: Seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5011:80