@url = http://localhost:5001

@email = tom.krasienko@gmail.pl
@password = StrongPass123!

###
# @name sign_in
POST {{url}}/owner-module/users/sign-in
Content-Type: application/json

{
    "email":"{{email}}",
    "password":"{{password}}"
}

###
@token = {{sign_in.response.body.$.token}}

### Companies
###
GET {{url}}/companies-module/companies?PageNumber=1&PageSize=10&Name=test
Authorization: bearer {{token}}

###
# @companyId = {{add_company.response.headers.x-resource-id}}
@companyId = 2c9c0c51-0c63-4daf-b4c3-d37c2e27bdfa

###
GET {{url}}/companies-module/companies/{{companyId}}
Authorization: Bearer {{token}}

###
# @name add_company
POST {{url}}/companies-module/companies/add
Authorization: bearer {{token}}
Content-Type: application/json

{
    "name":"My test client",
    "slaTime":"08:00:00",
    "emailDomain":"test.com"
}

### Employees
###
# @name get_by_id
GET {{url}}/companies-module/employees/{{employeeId}}
Authorization: bearer {{token}}

###
# @name add_employee
POST {{url}}/companies-module/employees/companies/{{companyId}}/add
Authorization: bearer {{token}}
Content-Type: application/json

{
    "email": "jakub.michalak@test.com",
    "phoneNumber": "555000111"
}

###
@employeeId = {{add_employee.response.headers.x-resource-id}}
# @employeeId = 


###
POST {{url}}/companies-module/projects/companies/{{companyId}}/add
Authorization: bearer {{token}}
Content-Type: application/json

{
    "title":"First Project",
    "description":"Description"
}