@url = http://localhost:5001
@manager_email = joe.doe@working-good.pl
@manager_password = StrongPass123!

@user_email = rajon.teller@working-good.pl
@user_password = VeryStrongPass123!

###
GET {{url}}/companies-module

###
GET {{url}}/messages-module

###
GET {{url}}/notifications-module

###
GET {{url}}/owner-module

###
GET {{url}}/tickets-module

###
GET {{url}}/activities-module

### 
POST {{url}}/owner-module/owner/add
Content-Type: application/json

{
    "name":"MyCompany"
}

###
POST {{url}}/owner-module/users/sign-up
Content-Type: application/json

{
    "email":"{{manager_email}}",
    "firstName":"Joe",
    "lastName":"Doe",
    "password":"{{manager_password}}",
    "role":"Manager"
}

@manager_verification_token = BEjfwH4FBHPX9oJCFpksoUY1NEbDm+ZijwRO0Qa7ePHX7Hkcu9RevNOPwELhfUgi9TWQiLi8pDB6Z1XwJN51PA

###
POST {{url}}/owner-module/users/verify
Content-Type: application/json

{
    "token":"{{manager_verification_token}}"
}

###
# @name sign_in_manager
POST {{url}}/owner-module/users/sign-in
Content-Type: application/json

{
    "email":"{{manager_email}}",
    "password":"{{manager_password}}"
}

###
@token_manager = {{sign_in_manager.response.body.$.token}}

###
# @name me_manager
GET {{url}}/owner-module/users/me
Authorization: Bearer {{token_manager}}

###
@managerId = {{me_manager.response.body.$.id}}


###
POST {{url}}/owner-module/users/sign-up
Content-Type: application/json

{
    "email":"{{user_email}}",
    "firstName":"Rajon",
    "lastName":"Teller",
    "password":"{{user_password}}",
    "role":"User"
}

###
@user_verification_token = MWXsKj8VSnyhZ4P8nrDq2jamhR6xcfKtSIVxC4Ne2y6hPISU9K7RgoqsB9Iloefo1uHE4AfF27KfJyLd8XDJg

###
POST {{url}}/owner-module/users/verify
Content-Type: application/json

{
    "token":"{{user_verification_token}}"
}

###
# @name sign_in_user
POST {{url}}/owner-module/users/sign-in
Content-Type: application/json

{
    "email":"{{user_email}}",
    "password":"{{user_password}}"
}

###
@token_user = {{sign_in_user.response.body.$.token}}

###
# @name me_user
GET {{url}}/owner-module/users/me
Authorization: bearer {{token_user}}

###
@userId = {{me_user.response.body.$.id}}

###
# @name add_company
POST {{url}}/companies-module/companies/add
Authorization: bearer {{token_manager}}
Content-Type: application/json

{
    "name":"SecondClient",
    "slaTime":"08:00:00",
    "emailDomain":"outlook.com"
}

###
@companyId = {{add_company.response.headers.x-resource-id}}

###
# @name add_project
POST {{url}}/companies-module/projects/companies/{{companyId}}/add
Authorization: bearer {{token_manager}}
Content-Type: application/json

{
    "title":"First Project",
    "description":"Description"
}

###
@projectId = {{add_project.response.headers.x-resource-id}}

###
# @name add_employee
POST {{url}}/companies-module/employees/companies/{{companyId}}/add
Authorization: bearer {{token_manager}}
Content-Type: application/json

{
    "email": "tom.krasienko@outlook.com",
    "phoneNumber": "555000111"
}

###
@employeeId = {{add_employee.response.headers.x-resource-id}}

###
# @name add_user_to_group
POST {{url}}/owner-module/groups/{{projectId}}/add-user
Authorization: bearer {{token_manager}}
Content-Type: application/json

{
    "userId":"{{userId}}"
}

###
# @name ticket_add
POST {{url}}/tickets-module/tickets/add
Authorization: bearer {{token_user}}
Content-Type: application/json

{
    "subject": "Can not open system!",
    "content": "After comming to address i see only alert about problems with app"
}

###
@ticket_id = {{ticket_add.response.headers.x-resource-id}}

###
GET {{url}}/tickets-module/tickets/{{ticket_id}}
Authorization: bearer {{token_manager}}

###
# @name assign_user
PATCH {{url}}/tickets-module/tickets/{{ticket_id}}/user/{{userId}}
Authorization: bearer {{token_user}}

###
GET {{url}}/tickets-module/tickets/{{ticket_id}}
Authorization: bearer {{token_manager}}

###
# @name assign_employee
PATCH {{url}}/tickets-module/tickets/{{ticket_id}}/employee/{{employeeId}}
Authorization: bearer {{token_user}}

###
GET {{url}}/tickets-module/tickets/{{ticket_id}}
Authorization: bearer {{token_manager}}

###
PATCH {{url}}/tickets-module/tickets/{{ticket_id}}/project/{{projectId}}
Authorization: bearer {{token_user}}

###
GET {{url}}/tickets-module/tickets/{{ticket_id}}
Authorization: bearer {{token_manager}}

###
PATCH {{url}}/tickets-module/tickets/{{ticket_id}}/change-priority
Authorization: bearer {{token_user}}

###
GET {{url}}/tickets-module/tickets/{{ticket_id}}
Authorization: bearer {{token_manager}}



###
POST {{url}}/activities-module/activities/add
Authorization: bearer {{token}}
Content-Type: application/json

{
    "userId": "{{userId}}",
    "ticketId": "{{ticketId}}",
    "content": "Test activity",
    "timeFrom": "2019-08-24T14:15:22Z",
    "timeTo": "2019-08-24T14:40:22Z",
    "isPaid": true
}



