@url = http://localhost:5001
@email = tom.krasienko@gmail.pl
@password = StrongPass123!

###
GET {{url}}/companies-module

###
GET {{url}}/messages-module

###
GET {{url}}/notifications-module

###
GET {{url}}/owner-module

###
GET {{url}}/tickets-module


### 
POST {{url}}/owner-module/owner/add
Content-Type: application/json

{
    "name":"MyCompany"
}

###
POST {{url}}/owner-module/users/sign-up
Content-Type: application/json

{
    "email":"{{email}}",
    "firstName":"Joe",
    "lastName":"Doe",
    "password":"{{password}}",
    "role":"Manager"
}

###
POST {{url}}/owner-module/users/verify
Content-Type: application/json

{
    "token":"00000000-0000-0000-0000-000000000000"
}

###
# @name sign_in
POST {{url}}/owner-module/users/sign-in
Content-Type: application/json

{
    "email":"{{email}}",
    "password":"{{password}}"
}

###
@token = {{sign_in.response.body.$.token}}

###
GET {{url}}/owner-module/owner
Authorization: bearer {{token}}

###
# @name me
GET {{url}}/owner-module/users/me
Authorization: Bearer {{token}}

###
@userId = {{me.response.body.$.id}}

###
GET {{url}}/owner-module/users/{{userId}}/active
Authorization: bearer {{token}}

###
# @name add_company
POST {{url}}/companies-module/companies/add
Authorization: bearer {{token}}
Content-Type: application/json

{
    "name":"SecondClient",
    "slaTime":"08:00:00",
    "emailDomain":"outlook.com"
}

###
@companyId = {{add_company.response.headers.x-resource-id}}

###
POST {{url}}/companies-module/projects/companies/{{companyId}}/add
Authorization: bearer {{token}}
Content-Type: application/json

{
    "title":"First Project",
    "description":"Description"
}

###
# @name add_employee
POST {{url}}/companies-module/employees/companies/{{companyId}}/add
Authorization: bearer {{token}}
Content-Type: application/json

{
    "email": "tom.krasienko@outlook.com",
    "phoneNumber": "555000111"
}

###
@employeeId = {{add_employee.response.headers.x-resource-id}}


###
# @name ticket_add
POST {{url}}/tickets-module/tickets/add
Authorization: bearer {{token}}
Content-Type: application/json

{
    "subject": "Can not open system!",
    "content": "After comming to address i see only alert about problems with app",
    "state": "New",
    "isPriority": true,
    "assignedEmployee": "{{employeeId}}",
    "assignedUser": "{{userId}}"
}

###
@ticketId = {{ticket_add.response.headers.x-resource-id}}

###
GET {{url}}/tickets-module/tickets/{{ticketId}}
Authorization: bearer {{token}}

###
POST {{url}}/tickets-module/messages/ticket/{{ticketId}}/add
Authorization: bearer {{token}}
Content-Type: application/json

{
    "Content":"Przyjąłem"
}

###
POST {{url}}/tickets-module/activities/ticket/{{ticketId}}/add
Authorization: bearer {{token}}
Content-Type: application/json

{
  "ticketId": "{{ticketId}}",
  "timeFrom": "2024-04-17T16:11:00",
  "timeTo": "2024-04-17T16:30:00",
  "note": "Restarted database",
  "isPaid": true,
  "userId": "{{userId}}"
}


###
GET {{url}}/tickets-module/tickets?pageSize=3&pageNumber=1&subject=ticket
Authorization: bearer {{token}}



###Another path
###
PATCH {{url}}/companies-module/employees/deactivate/4d83ebed-5980-4363-a64f-acca5449539b
Authorization: bearer {{token}}
Content-Type: application/json

{
    "substitutionEmployeeId":"b602fd3b-9d9f-4f92-8465-b1ff85338e78"
}