// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wg.modules.wiki.infrastructure.DAL;

#nullable disable

namespace wg.modules.wiki.infrastructure.DAL.Migrations
{
    [DbContext(typeof(WikiDbContext))]
    [Migration("20240606125335_fixed_origins")]
    partial class fixed_origins
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wiki")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("wg.modules.wiki.domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Notes", "wiki");
                });

            modelBuilder.Entity("wg.modules.wiki.domain.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Sections", "wiki");
                });

            modelBuilder.Entity("wg.modules.wiki.domain.Entities.Note", b =>
                {
                    b.HasOne("wg.modules.wiki.domain.Entities.Section", null)
                        .WithMany("Notes")
                        .HasForeignKey("SectionId");

                    b.OwnsOne("wg.modules.wiki.domain.ValueObjects.Note.Origin", "Origin", b1 =>
                        {
                            b1.Property<Guid>("NoteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Id")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("OriginId");

                            b1.Property<string>("Type")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("OriginType");

                            b1.HasKey("NoteId");

                            b1.ToTable("Notes", "wiki");

                            b1.WithOwner()
                                .HasForeignKey("NoteId");
                        });

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("wg.modules.wiki.domain.Entities.Section", b =>
                {
                    b.HasOne("wg.modules.wiki.domain.Entities.Section", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("wg.modules.wiki.domain.Entities.Section", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
